- job:
    name: "{{itrust_fuzzer_name}}"
    scm: 
      - git: 
          url: git@github.com:sseelam2/iTrust2-v4.git
          branches: 
            - origin/fuzzer
            - ${sha1}
    triggers:
      - pollscm:
          cron: ""

    builders:
      - ansible-playbook:
          playbook: "/var/lib/jenkins/itrust_build_fuzzer.yml"
          inventory-type: "path"
          inventory:
            path: "~/local_inventory"

      - shell: |
          sleep 20s
          cd /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/iTrust2-v4/iTrust2/ 
          sudo mvn -f pom-data.xml process-test-classes
          cd /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/iTrust2-v4/iTrust2/ 
          sudo mvn clean test verify checkstyle:checkstyle

    publishers:
      - postbuildscript:
          builders:
            - role: BOTH
              build-on:
                - SUCCESS
                - FAILURE
              build-steps:
                - shell: |
                    today=`date +%Y-%m-%d.%H:%M:%S`
                    sudo cp -R /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/iTrust2-v4/iTrust2/target/surefire-reports /home/vagrant/fuzzer_test_reports/$today/
                    sudo rm -rf /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/