- job:
    name: "{{itrust_fuzzer_name}}"
    scm: 
      - git: 
          
          url: http://{{gituser}}:{{gitpass}}@github.com/sseelam2/iTrust2-v4.git
          branches: 
            - origin/fuzzer
            - ${sha1}
    triggers:
      - pollscm:
          cron: ""

    builders:

      - shell: |
          sudo ansible-playbook /var/lib/jenkins/itrust_build_fuzzer.yml -i ~/local_inventory

  
    publishers:
      - jacoco:
          changeBuildStatus: false
          exec-pattern: '**/**.exec'
          class-pattern: '**/classes'
          source-pattern: '**/src'
          update-build-status: true
          exclusion-pattern: '**/*Test*.class'
          buildOverBuild: true
          
      - postbuildscript:
          builders:
            - role: BOTH
              build-on:
                - SUCCESS
                - FAILURE
              build-steps:
                - shell: |
                    today=`date +%Y-%m-%d.%H:%M:%S`
                    sudo cp -R /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/iTrust2/target/surefire-reports /home/vagrant/fuzzer_test_reports/$today/
                    sudo rm -rf /var/lib/jenkins/workspace/{{itrust_fuzzer_name}}/
                    touch /home/vagrant/report.txt && rm /home/vagrant/report.txt
                    cd /home/vagrant
                    sudo npm install
                    sudo node priority.js
                    

                    


