- job:
    name: "{{itrust_name}}"
    description: 'creating job'
    project-type: freestyle
    builders:
        - shell: |  
            sudo ansible-playbook /var/lib/jenkins/itrust_build_tmp.yml -i ~/local_inventory
            sleep 20s 
            cd /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/ 
            sudo mvn -f pom-data.xml process-test-classes
            cd /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/ && sudo mvn clean test verify checkstyle:checkstyle
    publishers:
        - jacoco:
            exec-pattern: '**/**.exec'
            class-pattern: '**/classes'
            source-pattern: '**/src'
            update-build-status: true
            exclusion-pattern: '**/*Test*.class'
        - checkstyle:
            pattern: '**/checkstyle-result.xml'
            can-run-on-failed: true
            should-detect-modules: false
            health-threshold: 'high'

        
