- name: Copy tokens from local to the Workers
  copy:
    src: "~/DevopsProject/milestone3/ansible_scripts/kubernetes/roles/master_setup/templates/joinTokens.sh"
    dest: "/root/kubernetes/joinTokens.sh"
  

- name: chmod the shell script
  shell: "chmod +x joinTokens.sh"
  args:
    chdir: "/root/kubernetes/"

- name: Execute the script to join the workers to Cluster
  shell: "sh joinTokens.sh"
  args:
    chdir: "/root/kubernetes/"
  become: yes

