---
    - name: check if Project folder exists or create it
      file:
        path: "{{ itrust_dir }}"
        state: directory
        mode: 0775
      

    - name: check if itrust workspace folder exists
      stat:
        path: "{{ itrust_dir }}/iTrust2-v4"
      register: workspace

    - name: delete if the itrust directory exists
      file:
        state: absent
        path: "{{ itrust_dir }}/iTrust2-v4"
      when: workspace.stat.exists
      become: true
        
    - name: Clone itrust Git Repository
      shell: |
        cd {{ itrust_dir }}
        git clone https://github.com/sseelam2/iTrust2-v4.git

    - name: check if itrust bare repo exists
      file:
        path: "{{ itrust_dir }}/itrust.git"
        state: directory

    - name: make itrust bare repo
      shell: |
        cd "{{ itrust_dir }}/itrust.git"
        sudo git init --bare 

    - name: set itrust.git to be prod
      shell: |
        cd "{{ itrust_dir }}/iTrust2-v4"
        sudo git remote add prod {{ itrust_dir }}/itrust.git
      

    - name: adding post-receive git hook
      template:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone3/ansible_scripts/roles/iTrust_deploy/templates/post-receive"
        dest: "{{ itrust_dir }}/itrust.git/hooks/post-receive"
        mode: 0767
      become: true 

    - name: Add trigger.js file to the git Repo
      copy:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone3/ansible_scripts/roles/iTrust_deploy/templates/trigger.js"
        dest: "{{ itrust_dir }}/iTrust2-v4/trigger.js"
        mode: 0666

    - name: Add package.json file to the git Repo
      copy:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone3/ansible_scripts/roles/iTrust_deploy/templates/package.json"
        dest: "{{ itrust_dir }}/iTrust2-v4/package.json"
        mode: 0666

    - name: install pip
      apt:
        name: python-pip
      become: true
    - name: install pexpect
      pip:
        name: pexpect
      become: true

    - name: Git add and checkout master
      shell: |
        cd {{ itrust_dir }}/iTrust2-v4
        sudo npm install
        sudo npm install random-js
        npm install jenkins-api
        sudo git checkout master 
        sudo touch deployfile6
        sudo git add deployfile6
        sudo git commit -m "added new file"

    - name:  Git push to origin
      expect:
        command:  git push
        responses:
          "Username for 'https://github.com':": "{{ git_user }}"
          "Password for 'https://sseelam2@github.com':": "{{ git_pass }}"
        chdir: "{{ itrust_dir }}/iTrust2-v4"
      register: output_var
      become: true


    - name: Git push to prod
      expect:
        command: git push prod master
        responses:
          "Username for 'https://github.com':": "{{ git_user }}"
          "Password for 'https://sseelam2@github.com':": "{{ git_pass }}"
        chdir: "{{ itrust_dir }}/iTrust2-v4"
      register: output_var1
      become: true


    - name: debug messages
      debug:
        msg: "{{ output_var }}"

    - name: debug messages
      debug:
        msg: "{{ output_var1 }}"
   