- job:
    name: "{{itrust_name}}"
    description: 'creating job'
    project-type: freestyle
    builders:
      - shell: |  
            sudo su
            git clone http://github.com/sseelam2/iTrust2-v4.git
            sed -i 's/username root/username mysql-server/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
            sed -i 's/password/password {{ mysql_password }}/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
            sed -i 's/username/username swarna.ragz@gmail.com/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
            sed -i 's/password/password Ramswar3151\&/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
            cd /var/lib/jenkins/workspace/itrust_job/iTrust2-v4/iTrust2/src/main/java
            cp /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/db.properties.template /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/db.properties
            cp /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties        
            cd /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/
            mvn clean test verify checkstyle:checkstyle
    publishers:
        - postbuildscript:
            builders:
                - role: BOTH
                  build-on: 
                      - SUCCESS 
                  build-steps:     
                      - shell: 'ansible-playbook /jenkins/iTrust_deploy.yml -i /jenkins/inventory'    

