- job:
    name: "{{itrust_name}}"
    description: 'creating job'
    project-type: freestyle
    builders:
      - shell: |  
            git clone http://github.com/sseelam2/iTrust2-v4.git
            sudo sed -i 's/username root/username mysql-server/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
            sudo sed -i 's/password/password {{ mysql_password }}/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
            sudo sed -i 's/from/from No-Reply/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
            sudo sed -i 's/user/user harish4795/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
            sudo sed -i 's/password/password uppercasee/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
            cd /var/lib/jenkins/workspace/itrust_job/iTrust2-v4/iTrust2/src/main/java
            sudo cp /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/db.properties.template /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/db.properties
            sudo cp /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties        
            cd /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/
            mvn -f pom-data.xml process-test-classes
            cd /var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/   
            mvn clean test verify checkstyle:checkstyle
    publishers:
        - postbuildscript:
            builders:
                - role: BOTH
                  build-on: 
                      - SUCCESS 
                  build-steps:     
                      - shell: 'ansible-playbook /jenkins/iTrust_deploy.yml -i /jenkins/inventory'    

