- job:
    name: "{{ checkboxio_job_name }}"
    description: 'creating job'
    project-type: freestyle
    builders:
      - shell: |
          sudo su 
          git clone https://github.com/sseelam2/checkbox.io.git
          cd /var/lib/jenkins/workspace/checkbox_job/checkbox.io/server-side/site
          sudo npm install
    publishers:
        - postbuildscript:
            builders:
                - role: BOTH
                  build-on: 
                      - SUCCESS 
                  build-steps:     
                      - shell: 'sudo ansible-playbook /jenkins/deploy_checkbox.yml -i /jenkins/inventory'
                

