---

    - name: Update and Upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Git Package 
      apt: name=git state=present update_cache=true

    - name: Update and Upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600


    - name: Clone checkbox.io git repository
      git:
        repo: 'http://github.com/sseelam2/iTrust2-v4.git'
        dest: /home/vagrant/iTrust
        update: no

    - name: makes changes to config
      shell: |
        sed -i 's/username root/username mysql-server/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
        sed -i 's/password/password root/' "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/iTrust2/src/main/java/db.properties.template"
        sed -i 's/username/username swarna.ragz@gmail.com/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"
        sed -i 's/password/password Ramswar3151\&/' "/var/lib/jenkins/workspace/{{itrust_name}}/iTrust2-v4/iTrust2/src/main/java/email.properties.template"

    - name: copy necessary files to destination
      copy: 
        src: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties.template
        dest: /home/vagrant/iTrust/iTrust2/src/main/java/db.properties  
        remote_src: yes 
      become: yes

    - name: copy necessary files to destination
      copy: 
        src: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties.template
        dest: /home/vagrant/iTrust/iTrust2/src/main/java/email.properties  
        remote_src: yes 
      become: yes

    - name: mysql.conf file changes
      lineinfile:
          path: /etc/mysql/mysql.conf.d/mysqld.cnf
          line: skip-grant-tables
          insertafter: skip-external-locking

    - name: Restart mysql
      service: name=mysql state=restarted
      become: yes


    - name: building mvn
      command: mvn clean
      args:
        chdir: /home/vagrant/iTrust/iTrust2
      become: true

    - name: building mvn
      command: mvn -f pom-data.xml process-test-classes
      args:
        chdir: /home/vagrant/iTrust/iTrust2
      become: true

    - name: Update and Upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Running jetty
      shell: |
        cd /home/vagrant/iTrust/iTrust2
        nohup sudo mvn jetty:run >/dev/null 2>&1 &
...