- hosts: localhost
  tasks:
    
      - name: Bake Jenkins Server
        shell: |
          cd ~/DevopsProject/milestone2/servers/jenkins
          baker bake
        become: true

      - name: Bake Checkboxio Server
        shell: |
          cd ~/DevopsProject/milestone2/servers/checkbox
          baker bake
        become: true

      - name: Bake ITrust Server
        shell: |
          cd ~/DevopsProject/milestone2/servers/itrust
          baker bake
        become: true

      - name: Generate SSH key for servers
        expect:
          command: ssh-keygen -t rsa -b 4096 -C "ssh_rsa" -f ssh_rsa
          responses:
            'Enter passphrase \(empty for no passphrase\):': ''
            'Enter same passphrase again:': ''
        args:
          creates: ~/.ssh/ssh_rsa

 