- job:
    name: "{{ checkboxio_job_name }}"
    description: 'creating checkbox.io job'
    project-type: freestyle
    builders:
      - shell: |
          sudo su
          git clone https://github.com/sseelam2/checkbox.io.git
          cd /var/lib/jenkins/workspace/checkbox_job/checkbox.io/server-side/site
          sudo cp /var/lib/jenkins/workspace/checkbox_job/checkbox.io/local-conf/nginx.conf /etc/nginx/nginx.conf
          sudo chmod 644 /etc/nginx/nginx.conf
          sudo cp /var/lib/jenkins/workspace/checkbox_job/checkbox.io/local-conf/default /etc/nginx/sites-available/default 
          sudo chmod 644 /etc/nginx/sites-available/default
          sudo npm install
          sudo npm test
    publishers:
        - postbuildscript:
            builders:
                - role: BOTH
                  build-on: 
                      - SUCCESS 
                  build-steps:     
                      - shell: |
                            sudo ansible-playbook /var/lib/jenkins/provision.yml -i ~/local_inventory
                

