- job:
    name: "{{checkboxio_canary_job_name}}"
    scm: 
      - git: 
          
          url: http://{{gituser}}:{{gitpass}}@github.com/sseelam2/checkbox.git
          branches: 
            - origin/canary
            - ${sha1}
    triggers:
      - pollscm:
          cron: ""

    builders:
      - shell: |
            sudo ansible-playbook /var/lib/jenkins/checkbox_build_deploy.yml -i /var/lib/jenkins/local_inventory
 
    publishers:          
      - postbuildscript:
          builders:
            - role: BOTH
              build-on:
                - SUCCESS                
              build-steps:
                - shell: |
                    cd /home/vagrant
                    sudo python /home/vagrant/deploy/write_canary_inventory.py
                    sudo ansible-playbook /home/vagrant/deploy/deploy_canary_checkbox.yml -i /home/vagrant/deploy/checkbox_canary_inventory

                    

                    


