- name: check if itrust git folder exists
  stat:
    path: "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/"
  register: git

- name: delete if the itrust directory exists
  file:
    state: absent
    path: "/var/lib/jenkins/workspace/{{ itrust_name }}/iTrust2-v4/"
  when: git.stat.exists
  become: true


- name: build itrust job
  shell: 'java -jar jenkins-cli.jar -s {{ jenkins_url2 }}/ build {{ itrust_name }} --username {{ jenkins_user_name }} --password {{ jenkins_password }}'
  become: true