- job:
    name: "{{itrust_deploy_name}}"
    scm: 
      - git: 
          
          url: http://{{gituser}}:{{gitpass}}@github.com/sseelam2/iTrust2-v4.git
          branches: 
            - origin/master
            - ${sha1}
    triggers:
      - pollscm:
          cron: ""

    builders:
      - shell: |
            sudo ansible-playbook /var/lib/jenkins/itrust_build_deploy.yml -i ~/local_inventory
            sleep 20s 
            cd /var/lib/jenkins/workspace/{{itrust_deploy_name}}/iTrust2-v4/iTrust2/ 
            sudo mvn -f pom-data.xml process-test-classes
            cd /var/lib/jenkins/workspace/{{itrust_deploy_name}}/iTrust2-v4/iTrust2/ && sudo mvn clean test verify checkstyle:checkstyle
 
    publishers:          
      - postbuildscript:
          builders:
            - role: BOTH
              build-on:
                - SUCCESS                
              build-steps:
                - shell: |
                    sudo ansible-playbook /var/lib/jenkins/provision.yml -i ~/local_inventory
                    sleep 60s
                    cd /home/vagrant
                    sudo ansible-playbook /home/vagrant/deploy/iTrust_deploy.yml -i /home/vagrant/deploy/itrust_inventory

                    

                    


