---
  checkboxio_job_name: "checkbox_job"
  jenkins_url: "http://localhost:8080"
  jenkins_password: "Sunmoon@12"
  jenkins_user_name: "jenkins"
  dbuser: "admin"
  dbpwd: "admin"
  mailuser: "devopshrss"
  mailpwd: "smsmmsme"

...