---
- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

- name: add java repo
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'


- name: Installing Open JDK
  shell: |
    sudo apt-get update
    sudo apt-get install openjdk-8-jdk -y





