---  
- name: build itrust job
  shell: 'java -jar jenkins-cli.jar -s {{ jenkins_build_url }}/ build {{ checkboxio_job_name }} --username {{ jenkins_user_name }} --password {{ jenkins_password }}'
  become: true
