---
    - name: check if itrust workspace folder exists
      stat:
        path: "{{ itrust_dir }}/iTrust2-v4"
      register: workspace

    - name: delete if the itrust directory exists
      file:
        state: absent
        path: "{{ itrust_dir }}/iTrust2-v4"
      when: workspace.stat.exists
      

    
    - name: Clone itrust Git Repository
      shell: |
        cd {{ itrust_dir }}
        git clone https://github.com/sseelam2/iTrust2-v4.git
      

    - name: adding pre-push git hook
      template:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone2/ansible_scripts/roles/iTrust_fuzzer/templates/pre-push"
        dest: "{{ itrust_dir }}/iTrust2-v4/.git/hooks/pre-push"
        mode: 0767

    - name: Add Fuzzer.js file to the git Repo
      copy:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone2/ansible_scripts/roles/iTrust_fuzzer/templates/fuzzer.js"
        dest: "{{ itrust_dir }}/iTrust2-v4/fuzzer.js"
        mode: 0666

    - name: Add package.json file to the git Repo
      copy:
        src: "{{ devops_milestone_dir }}/DevopsProject/milestone2/ansible_scripts/roles/iTrust_fuzzer/templates/package.json"
        dest: "{{ itrust_dir }}/iTrust2-v4/package.json"
        mode: 0666

    - name: Git add and checkout master
      shell: |
        cd ~/Project/iTrust2-v4
        sudo npm install 
        sudo npm install random-js
        sudo git checkout master 
        sudo touch testfile5
        sudo git add testfile5
        sudo git commit -m \"commit after changes\" 
        git push
      register: output_var

    - name: debug messages
      debug:
        msg: "{{ output_var }}"
